"""add description_template table

Revision ID: 69899b5f9a86
Revises: 6bec71f88a92
Create Date: 2026-02-23 22:16:56.863168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69899b5f9a86'
down_revision = '6bec71f88a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description_template',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inventory_product_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('inventory_product_id_key'), ['product_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('description_template')
    # ### end Alembic commands ###
